const DEFAULT_SUPABASE_URL = 'https://dwkavovavoidoxrckimj.supabase.co'
const DEFAULT_SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3a2F2b3Zhdm9pZG94cmNraW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODk0NzUsImV4cCI6MjA3Mzc2NTQ3NX0.TwQSLH9gWJ81sj57l_u-QmLdQEyud9tfA0ZnwRHoOzQ'
const DEFAULT_SUPABASE_SERVICE_ROLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3a2F2b3Zhdm9pZG94cmNraW1qIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODE4OTQ3NSwiZXhwIjoyMDczNzY1NDc1fQ._QfZsfntL4RAynyo32B3Ufcgr2lLp2JPLxEwxzCisJE'

export const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ||
  process.env.SUPABASE_URL ||
  DEFAULT_SUPABASE_URL

export const SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  process.env.SUPABASE_ANON_KEY ||
  DEFAULT_SUPABASE_ANON_KEY

export const SUPABASE_SERVICE_ROLE_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY ||
  process.env.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY ||
  DEFAULT_SUPABASE_SERVICE_ROLE_KEY

export const HAS_SUPABASE_SERVICE_ROLE_KEY =
  SUPABASE_SERVICE_ROLE_KEY.trim().length > 0

